version: "3.9"
services:
  app:
    build: .
    container_name: graph_service_app
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - ./:/app
  redis:
    image: redis:7-alpine
    container_name: graph_service_redis
    ports:
      - "6379:6379"

